//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace RMSExternalApi.PostmanSv {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PostmanServiceSoap", Namespace="http://tempuri.org/")]
    public partial class PostmanService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SendHaloMgsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendHaloMgsWithScreenShotOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendHaloMgsWithFreeSpaceOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendHaloMgsWithForwardOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrderStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertSignHistoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmpNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmpInfomationOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmp_AgentOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmpAgentOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmpLevelOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmpManagersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmpMailOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExecuteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PostmanService() {
            this.Url = global::RMSExternalApi.Properties.Settings.Default.MedicineApi_PostmanSv_PostmanService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendHaloMgsCompletedEventHandler SendHaloMgsCompleted;
        
        /// <remarks/>
        public event SendHaloMgsWithScreenShotCompletedEventHandler SendHaloMgsWithScreenShotCompleted;
        
        /// <remarks/>
        public event SendHaloMgsWithFreeSpaceCompletedEventHandler SendHaloMgsWithFreeSpaceCompleted;
        
        /// <remarks/>
        public event SendHaloMgsWithForwardCompletedEventHandler SendHaloMgsWithForwardCompleted;
        
        /// <remarks/>
        public event UpdateOrderCompletedEventHandler UpdateOrderCompleted;
        
        /// <remarks/>
        public event GetOrderStatusCompletedEventHandler GetOrderStatusCompleted;
        
        /// <remarks/>
        public event InsertSignHistoryCompletedEventHandler InsertSignHistoryCompleted;
        
        /// <remarks/>
        public event GetEmpNameCompletedEventHandler GetEmpNameCompleted;
        
        /// <remarks/>
        public event GetEmpInfomationCompletedEventHandler GetEmpInfomationCompleted;
        
        /// <remarks/>
        public event GetEmp_AgentCompletedEventHandler GetEmp_AgentCompleted;
        
        /// <remarks/>
        public event GetEmpAgentCompletedEventHandler GetEmpAgentCompleted;
        
        /// <remarks/>
        public event GetEmpLevelCompletedEventHandler GetEmpLevelCompleted;
        
        /// <remarks/>
        public event GetEmpManagersCompletedEventHandler GetEmpManagersCompleted;
        
        /// <remarks/>
        public event GetEmpMailCompletedEventHandler GetEmpMailCompleted;
        
        /// <remarks/>
        public event SelectCompletedEventHandler SelectCompleted;
        
        /// <remarks/>
        public event ExecuteCompletedEventHandler ExecuteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendHaloMgs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendHaloMgs(string _SystemName, string _DocNO, string _SignEmpNo, string _CallBackUrl, string _HaloMgs, string _JsonShowData) {
            object[] results = this.Invoke("SendHaloMgs", new object[] {
                        _SystemName,
                        _DocNO,
                        _SignEmpNo,
                        _CallBackUrl,
                        _HaloMgs,
                        _JsonShowData});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendHaloMgsAsync(string _SystemName, string _DocNO, string _SignEmpNo, string _CallBackUrl, string _HaloMgs, string _JsonShowData) {
            this.SendHaloMgsAsync(_SystemName, _DocNO, _SignEmpNo, _CallBackUrl, _HaloMgs, _JsonShowData, null);
        }
        
        /// <remarks/>
        public void SendHaloMgsAsync(string _SystemName, string _DocNO, string _SignEmpNo, string _CallBackUrl, string _HaloMgs, string _JsonShowData, object userState) {
            if ((this.SendHaloMgsOperationCompleted == null)) {
                this.SendHaloMgsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendHaloMgsOperationCompleted);
            }
            this.InvokeAsync("SendHaloMgs", new object[] {
                        _SystemName,
                        _DocNO,
                        _SignEmpNo,
                        _CallBackUrl,
                        _HaloMgs,
                        _JsonShowData}, this.SendHaloMgsOperationCompleted, userState);
        }
        
        private void OnSendHaloMgsOperationCompleted(object arg) {
            if ((this.SendHaloMgsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendHaloMgsCompleted(this, new SendHaloMgsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendHaloMgsWithScreenShot", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendHaloMgsWithScreenShot(string _SystemName, string _DocNO, string _SignEmpNo, string _CallBackUrl, bool _AllowForward, string _HaloMgs, string _JsonShowData, string _ScreenShotUrl) {
            object[] results = this.Invoke("SendHaloMgsWithScreenShot", new object[] {
                        _SystemName,
                        _DocNO,
                        _SignEmpNo,
                        _CallBackUrl,
                        _AllowForward,
                        _HaloMgs,
                        _JsonShowData,
                        _ScreenShotUrl});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendHaloMgsWithScreenShotAsync(string _SystemName, string _DocNO, string _SignEmpNo, string _CallBackUrl, bool _AllowForward, string _HaloMgs, string _JsonShowData, string _ScreenShotUrl) {
            this.SendHaloMgsWithScreenShotAsync(_SystemName, _DocNO, _SignEmpNo, _CallBackUrl, _AllowForward, _HaloMgs, _JsonShowData, _ScreenShotUrl, null);
        }
        
        /// <remarks/>
        public void SendHaloMgsWithScreenShotAsync(string _SystemName, string _DocNO, string _SignEmpNo, string _CallBackUrl, bool _AllowForward, string _HaloMgs, string _JsonShowData, string _ScreenShotUrl, object userState) {
            if ((this.SendHaloMgsWithScreenShotOperationCompleted == null)) {
                this.SendHaloMgsWithScreenShotOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendHaloMgsWithScreenShotOperationCompleted);
            }
            this.InvokeAsync("SendHaloMgsWithScreenShot", new object[] {
                        _SystemName,
                        _DocNO,
                        _SignEmpNo,
                        _CallBackUrl,
                        _AllowForward,
                        _HaloMgs,
                        _JsonShowData,
                        _ScreenShotUrl}, this.SendHaloMgsWithScreenShotOperationCompleted, userState);
        }
        
        private void OnSendHaloMgsWithScreenShotOperationCompleted(object arg) {
            if ((this.SendHaloMgsWithScreenShotCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendHaloMgsWithScreenShotCompleted(this, new SendHaloMgsWithScreenShotCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendHaloMgsWithFreeSpace", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendHaloMgsWithFreeSpace(string _SystemName, string _DocNO, string _SignEmpNo, string _CallBackUrl, bool _AllowForward, string _HaloMgs, string _JsonShowData, string _ScreenShotUrl, string _FreeSpaceHtml) {
            object[] results = this.Invoke("SendHaloMgsWithFreeSpace", new object[] {
                        _SystemName,
                        _DocNO,
                        _SignEmpNo,
                        _CallBackUrl,
                        _AllowForward,
                        _HaloMgs,
                        _JsonShowData,
                        _ScreenShotUrl,
                        _FreeSpaceHtml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendHaloMgsWithFreeSpaceAsync(string _SystemName, string _DocNO, string _SignEmpNo, string _CallBackUrl, bool _AllowForward, string _HaloMgs, string _JsonShowData, string _ScreenShotUrl, string _FreeSpaceHtml) {
            this.SendHaloMgsWithFreeSpaceAsync(_SystemName, _DocNO, _SignEmpNo, _CallBackUrl, _AllowForward, _HaloMgs, _JsonShowData, _ScreenShotUrl, _FreeSpaceHtml, null);
        }
        
        /// <remarks/>
        public void SendHaloMgsWithFreeSpaceAsync(string _SystemName, string _DocNO, string _SignEmpNo, string _CallBackUrl, bool _AllowForward, string _HaloMgs, string _JsonShowData, string _ScreenShotUrl, string _FreeSpaceHtml, object userState) {
            if ((this.SendHaloMgsWithFreeSpaceOperationCompleted == null)) {
                this.SendHaloMgsWithFreeSpaceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendHaloMgsWithFreeSpaceOperationCompleted);
            }
            this.InvokeAsync("SendHaloMgsWithFreeSpace", new object[] {
                        _SystemName,
                        _DocNO,
                        _SignEmpNo,
                        _CallBackUrl,
                        _AllowForward,
                        _HaloMgs,
                        _JsonShowData,
                        _ScreenShotUrl,
                        _FreeSpaceHtml}, this.SendHaloMgsWithFreeSpaceOperationCompleted, userState);
        }
        
        private void OnSendHaloMgsWithFreeSpaceOperationCompleted(object arg) {
            if ((this.SendHaloMgsWithFreeSpaceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendHaloMgsWithFreeSpaceCompleted(this, new SendHaloMgsWithFreeSpaceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendHaloMgsWithForward", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendHaloMgsWithForward(string _SystemName, string _DocNO, string _SignEmpNo, string _CallBackUrl, bool _AllowForward, string _HaloMgs, string _JsonShowData, string _ScreenShotUrl) {
            object[] results = this.Invoke("SendHaloMgsWithForward", new object[] {
                        _SystemName,
                        _DocNO,
                        _SignEmpNo,
                        _CallBackUrl,
                        _AllowForward,
                        _HaloMgs,
                        _JsonShowData,
                        _ScreenShotUrl});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendHaloMgsWithForwardAsync(string _SystemName, string _DocNO, string _SignEmpNo, string _CallBackUrl, bool _AllowForward, string _HaloMgs, string _JsonShowData, string _ScreenShotUrl) {
            this.SendHaloMgsWithForwardAsync(_SystemName, _DocNO, _SignEmpNo, _CallBackUrl, _AllowForward, _HaloMgs, _JsonShowData, _ScreenShotUrl, null);
        }
        
        /// <remarks/>
        public void SendHaloMgsWithForwardAsync(string _SystemName, string _DocNO, string _SignEmpNo, string _CallBackUrl, bool _AllowForward, string _HaloMgs, string _JsonShowData, string _ScreenShotUrl, object userState) {
            if ((this.SendHaloMgsWithForwardOperationCompleted == null)) {
                this.SendHaloMgsWithForwardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendHaloMgsWithForwardOperationCompleted);
            }
            this.InvokeAsync("SendHaloMgsWithForward", new object[] {
                        _SystemName,
                        _DocNO,
                        _SignEmpNo,
                        _CallBackUrl,
                        _AllowForward,
                        _HaloMgs,
                        _JsonShowData,
                        _ScreenShotUrl}, this.SendHaloMgsWithForwardOperationCompleted, userState);
        }
        
        private void OnSendHaloMgsWithForwardOperationCompleted(object arg) {
            if ((this.SendHaloMgsWithForwardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendHaloMgsWithForwardCompleted(this, new SendHaloMgsWithForwardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateOrder(string _DocNO, string _SignEmpNo, string _HaloMgs) {
            object[] results = this.Invoke("UpdateOrder", new object[] {
                        _DocNO,
                        _SignEmpNo,
                        _HaloMgs});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateOrderAsync(string _DocNO, string _SignEmpNo, string _HaloMgs) {
            this.UpdateOrderAsync(_DocNO, _SignEmpNo, _HaloMgs, null);
        }
        
        /// <remarks/>
        public void UpdateOrderAsync(string _DocNO, string _SignEmpNo, string _HaloMgs, object userState) {
            if ((this.UpdateOrderOperationCompleted == null)) {
                this.UpdateOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOrderOperationCompleted);
            }
            this.InvokeAsync("UpdateOrder", new object[] {
                        _DocNO,
                        _SignEmpNo,
                        _HaloMgs}, this.UpdateOrderOperationCompleted, userState);
        }
        
        private void OnUpdateOrderOperationCompleted(object arg) {
            if ((this.UpdateOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateOrderCompleted(this, new UpdateOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOrderStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetOrderStatus(string _DocNO) {
            object[] results = this.Invoke("GetOrderStatus", new object[] {
                        _DocNO});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrderStatusAsync(string _DocNO) {
            this.GetOrderStatusAsync(_DocNO, null);
        }
        
        /// <remarks/>
        public void GetOrderStatusAsync(string _DocNO, object userState) {
            if ((this.GetOrderStatusOperationCompleted == null)) {
                this.GetOrderStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrderStatusOperationCompleted);
            }
            this.InvokeAsync("GetOrderStatus", new object[] {
                        _DocNO}, this.GetOrderStatusOperationCompleted, userState);
        }
        
        private void OnGetOrderStatusOperationCompleted(object arg) {
            if ((this.GetOrderStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrderStatusCompleted(this, new GetOrderStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertSignHistory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InsertSignHistory(string _OrderNo, string _ApproverId, string _ApproverTitle, string _ApproverSuggest, string _Status, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> _ApprovalTime) {
            object[] results = this.Invoke("InsertSignHistory", new object[] {
                        _OrderNo,
                        _ApproverId,
                        _ApproverTitle,
                        _ApproverSuggest,
                        _Status,
                        _ApprovalTime});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void InsertSignHistoryAsync(string _OrderNo, string _ApproverId, string _ApproverTitle, string _ApproverSuggest, string _Status, System.Nullable<System.DateTime> _ApprovalTime) {
            this.InsertSignHistoryAsync(_OrderNo, _ApproverId, _ApproverTitle, _ApproverSuggest, _Status, _ApprovalTime, null);
        }
        
        /// <remarks/>
        public void InsertSignHistoryAsync(string _OrderNo, string _ApproverId, string _ApproverTitle, string _ApproverSuggest, string _Status, System.Nullable<System.DateTime> _ApprovalTime, object userState) {
            if ((this.InsertSignHistoryOperationCompleted == null)) {
                this.InsertSignHistoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertSignHistoryOperationCompleted);
            }
            this.InvokeAsync("InsertSignHistory", new object[] {
                        _OrderNo,
                        _ApproverId,
                        _ApproverTitle,
                        _ApproverSuggest,
                        _Status,
                        _ApprovalTime}, this.InsertSignHistoryOperationCompleted, userState);
        }
        
        private void OnInsertSignHistoryOperationCompleted(object arg) {
            if ((this.InsertSignHistoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertSignHistoryCompleted(this, new InsertSignHistoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEmpName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetEmpName(string _EmpNo) {
            object[] results = this.Invoke("GetEmpName", new object[] {
                        _EmpNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetEmpNameAsync(string _EmpNo) {
            this.GetEmpNameAsync(_EmpNo, null);
        }
        
        /// <remarks/>
        public void GetEmpNameAsync(string _EmpNo, object userState) {
            if ((this.GetEmpNameOperationCompleted == null)) {
                this.GetEmpNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmpNameOperationCompleted);
            }
            this.InvokeAsync("GetEmpName", new object[] {
                        _EmpNo}, this.GetEmpNameOperationCompleted, userState);
        }
        
        private void OnGetEmpNameOperationCompleted(object arg) {
            if ((this.GetEmpNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmpNameCompleted(this, new GetEmpNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEmpInfomation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetEmpInfomation(string _EmpNo) {
            object[] results = this.Invoke("GetEmpInfomation", new object[] {
                        _EmpNo});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetEmpInfomationAsync(string _EmpNo) {
            this.GetEmpInfomationAsync(_EmpNo, null);
        }
        
        /// <remarks/>
        public void GetEmpInfomationAsync(string _EmpNo, object userState) {
            if ((this.GetEmpInfomationOperationCompleted == null)) {
                this.GetEmpInfomationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmpInfomationOperationCompleted);
            }
            this.InvokeAsync("GetEmpInfomation", new object[] {
                        _EmpNo}, this.GetEmpInfomationOperationCompleted, userState);
        }
        
        private void OnGetEmpInfomationOperationCompleted(object arg) {
            if ((this.GetEmpInfomationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmpInfomationCompleted(this, new GetEmpInfomationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEmp_Agent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetEmp_Agent(string _EmpNo) {
            object[] results = this.Invoke("GetEmp_Agent", new object[] {
                        _EmpNo});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetEmp_AgentAsync(string _EmpNo) {
            this.GetEmp_AgentAsync(_EmpNo, null);
        }
        
        /// <remarks/>
        public void GetEmp_AgentAsync(string _EmpNo, object userState) {
            if ((this.GetEmp_AgentOperationCompleted == null)) {
                this.GetEmp_AgentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmp_AgentOperationCompleted);
            }
            this.InvokeAsync("GetEmp_Agent", new object[] {
                        _EmpNo}, this.GetEmp_AgentOperationCompleted, userState);
        }
        
        private void OnGetEmp_AgentOperationCompleted(object arg) {
            if ((this.GetEmp_AgentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmp_AgentCompleted(this, new GetEmp_AgentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEmpAgent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetEmpAgent(string _EmpNo) {
            object[] results = this.Invoke("GetEmpAgent", new object[] {
                        _EmpNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetEmpAgentAsync(string _EmpNo) {
            this.GetEmpAgentAsync(_EmpNo, null);
        }
        
        /// <remarks/>
        public void GetEmpAgentAsync(string _EmpNo, object userState) {
            if ((this.GetEmpAgentOperationCompleted == null)) {
                this.GetEmpAgentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmpAgentOperationCompleted);
            }
            this.InvokeAsync("GetEmpAgent", new object[] {
                        _EmpNo}, this.GetEmpAgentOperationCompleted, userState);
        }
        
        private void OnGetEmpAgentOperationCompleted(object arg) {
            if ((this.GetEmpAgentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmpAgentCompleted(this, new GetEmpAgentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEmpLevel", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetEmpLevel(string _EmpNo) {
            object[] results = this.Invoke("GetEmpLevel", new object[] {
                        _EmpNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetEmpLevelAsync(string _EmpNo) {
            this.GetEmpLevelAsync(_EmpNo, null);
        }
        
        /// <remarks/>
        public void GetEmpLevelAsync(string _EmpNo, object userState) {
            if ((this.GetEmpLevelOperationCompleted == null)) {
                this.GetEmpLevelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmpLevelOperationCompleted);
            }
            this.InvokeAsync("GetEmpLevel", new object[] {
                        _EmpNo}, this.GetEmpLevelOperationCompleted, userState);
        }
        
        private void OnGetEmpLevelOperationCompleted(object arg) {
            if ((this.GetEmpLevelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmpLevelCompleted(this, new GetEmpLevelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEmpManagers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetEmpManagers(string _EmpNo) {
            object[] results = this.Invoke("GetEmpManagers", new object[] {
                        _EmpNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetEmpManagersAsync(string _EmpNo) {
            this.GetEmpManagersAsync(_EmpNo, null);
        }
        
        /// <remarks/>
        public void GetEmpManagersAsync(string _EmpNo, object userState) {
            if ((this.GetEmpManagersOperationCompleted == null)) {
                this.GetEmpManagersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmpManagersOperationCompleted);
            }
            this.InvokeAsync("GetEmpManagers", new object[] {
                        _EmpNo}, this.GetEmpManagersOperationCompleted, userState);
        }
        
        private void OnGetEmpManagersOperationCompleted(object arg) {
            if ((this.GetEmpManagersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmpManagersCompleted(this, new GetEmpManagersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEmpMail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetEmpMail(string _EmpNo) {
            object[] results = this.Invoke("GetEmpMail", new object[] {
                        _EmpNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetEmpMailAsync(string _EmpNo) {
            this.GetEmpMailAsync(_EmpNo, null);
        }
        
        /// <remarks/>
        public void GetEmpMailAsync(string _EmpNo, object userState) {
            if ((this.GetEmpMailOperationCompleted == null)) {
                this.GetEmpMailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmpMailOperationCompleted);
            }
            this.InvokeAsync("GetEmpMail", new object[] {
                        _EmpNo}, this.GetEmpMailOperationCompleted, userState);
        }
        
        private void OnGetEmpMailOperationCompleted(object arg) {
            if ((this.GetEmpMailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmpMailCompleted(this, new GetEmpMailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Select", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Select(string _ConStr, string _CMD) {
            object[] results = this.Invoke("Select", new object[] {
                        _ConStr,
                        _CMD});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SelectAsync(string _ConStr, string _CMD) {
            this.SelectAsync(_ConStr, _CMD, null);
        }
        
        /// <remarks/>
        public void SelectAsync(string _ConStr, string _CMD, object userState) {
            if ((this.SelectOperationCompleted == null)) {
                this.SelectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectOperationCompleted);
            }
            this.InvokeAsync("Select", new object[] {
                        _ConStr,
                        _CMD}, this.SelectOperationCompleted, userState);
        }
        
        private void OnSelectOperationCompleted(object arg) {
            if ((this.SelectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectCompleted(this, new SelectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Execute", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Execute(string _ConStr, string _CMD) {
            object[] results = this.Invoke("Execute", new object[] {
                        _ConStr,
                        _CMD});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ExecuteAsync(string _ConStr, string _CMD) {
            this.ExecuteAsync(_ConStr, _CMD, null);
        }
        
        /// <remarks/>
        public void ExecuteAsync(string _ConStr, string _CMD, object userState) {
            if ((this.ExecuteOperationCompleted == null)) {
                this.ExecuteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExecuteOperationCompleted);
            }
            this.InvokeAsync("Execute", new object[] {
                        _ConStr,
                        _CMD}, this.ExecuteOperationCompleted, userState);
        }
        
        private void OnExecuteOperationCompleted(object arg) {
            if ((this.ExecuteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExecuteCompleted(this, new ExecuteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void SendHaloMgsCompletedEventHandler(object sender, SendHaloMgsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendHaloMgsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendHaloMgsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void SendHaloMgsWithScreenShotCompletedEventHandler(object sender, SendHaloMgsWithScreenShotCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendHaloMgsWithScreenShotCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendHaloMgsWithScreenShotCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void SendHaloMgsWithFreeSpaceCompletedEventHandler(object sender, SendHaloMgsWithFreeSpaceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendHaloMgsWithFreeSpaceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendHaloMgsWithFreeSpaceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void SendHaloMgsWithForwardCompletedEventHandler(object sender, SendHaloMgsWithForwardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendHaloMgsWithForwardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendHaloMgsWithForwardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void UpdateOrderCompletedEventHandler(object sender, UpdateOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetOrderStatusCompletedEventHandler(object sender, GetOrderStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrderStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrderStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void InsertSignHistoryCompletedEventHandler(object sender, InsertSignHistoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertSignHistoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertSignHistoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetEmpNameCompletedEventHandler(object sender, GetEmpNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmpNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmpNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetEmpInfomationCompletedEventHandler(object sender, GetEmpInfomationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmpInfomationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmpInfomationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetEmp_AgentCompletedEventHandler(object sender, GetEmp_AgentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmp_AgentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmp_AgentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetEmpAgentCompletedEventHandler(object sender, GetEmpAgentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmpAgentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmpAgentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetEmpLevelCompletedEventHandler(object sender, GetEmpLevelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmpLevelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmpLevelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetEmpManagersCompletedEventHandler(object sender, GetEmpManagersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmpManagersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmpManagersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetEmpMailCompletedEventHandler(object sender, GetEmpMailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmpMailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmpMailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void SelectCompletedEventHandler(object sender, SelectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ExecuteCompletedEventHandler(object sender, ExecuteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExecuteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExecuteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591