//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace RMSExternalApi.sv {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FormServiceSoap", Namespace="http://tempuri.org/")]
    public partial class FormService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private FHWSoap fHWSoapValueField;
        
        private System.Threading.SendOrPostCallback ThrowInternetEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback ThrowPickListOperationCompleted;
        
        private System.Threading.SendOrPostCallback ThrowVoipOperationCompleted;
        
        private System.Threading.SendOrPostCallback ThrowWarelessOperationCompleted;
        
        private System.Threading.SendOrPostCallback ThrowUcOperationCompleted;
        
        private System.Threading.SendOrPostCallback ThrowWWWOperationCompleted;
        
        private System.Threading.SendOrPostCallback ThrowVPNOperationCompleted;
        
        private System.Threading.SendOrPostCallback ThrowTelPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback ThrowNewTelPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback ThrowSpecialNetOperationCompleted;
        
        private System.Threading.SendOrPostCallback ThrowNetworkOperationCompleted;
        
        private System.Threading.SendOrPostCallback ThrowNetletterOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidCostNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback NewValidCostNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidIENameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFormStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryAccoutByGroupOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FormService() {
            this.Url = global::RMSExternalApi.Properties.Settings.Default.MedicineApi_sv_FormService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public FHWSoap FHWSoapValue {
            get {
                return this.fHWSoapValueField;
            }
            set {
                this.fHWSoapValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ThrowInternetEmailCompletedEventHandler ThrowInternetEmailCompleted;
        
        /// <remarks/>
        public event ThrowPickListCompletedEventHandler ThrowPickListCompleted;
        
        /// <remarks/>
        public event ThrowVoipCompletedEventHandler ThrowVoipCompleted;
        
        /// <remarks/>
        public event ThrowWarelessCompletedEventHandler ThrowWarelessCompleted;
        
        /// <remarks/>
        public event ThrowUcCompletedEventHandler ThrowUcCompleted;
        
        /// <remarks/>
        public event ThrowWWWCompletedEventHandler ThrowWWWCompleted;
        
        /// <remarks/>
        public event ThrowVPNCompletedEventHandler ThrowVPNCompleted;
        
        /// <remarks/>
        public event ThrowTelPasswordCompletedEventHandler ThrowTelPasswordCompleted;
        
        /// <remarks/>
        public event ThrowNewTelPasswordCompletedEventHandler ThrowNewTelPasswordCompleted;
        
        /// <remarks/>
        public event ThrowSpecialNetCompletedEventHandler ThrowSpecialNetCompleted;
        
        /// <remarks/>
        public event ThrowNetworkCompletedEventHandler ThrowNetworkCompleted;
        
        /// <remarks/>
        public event ThrowNetletterCompletedEventHandler ThrowNetletterCompleted;
        
        /// <remarks/>
        public event ValidCostNoCompletedEventHandler ValidCostNoCompleted;
        
        /// <remarks/>
        public event NewValidCostNoCompletedEventHandler NewValidCostNoCompleted;
        
        /// <remarks/>
        public event ValidIENameCompletedEventHandler ValidIENameCompleted;
        
        /// <remarks/>
        public event GetFormStatusCompletedEventHandler GetFormStatusCompleted;
        
        /// <remarks/>
        public event QueryAccoutByGroupCompletedEventHandler QueryAccoutByGroupCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("FHWSoapValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ThrowInternetEmail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceOut ThrowInternetEmail(ServiceIn si) {
            object[] results = this.Invoke("ThrowInternetEmail", new object[] {
                        si});
            return ((ServiceOut)(results[0]));
        }
        
        /// <remarks/>
        public void ThrowInternetEmailAsync(ServiceIn si) {
            this.ThrowInternetEmailAsync(si, null);
        }
        
        /// <remarks/>
        public void ThrowInternetEmailAsync(ServiceIn si, object userState) {
            if ((this.ThrowInternetEmailOperationCompleted == null)) {
                this.ThrowInternetEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnThrowInternetEmailOperationCompleted);
            }
            this.InvokeAsync("ThrowInternetEmail", new object[] {
                        si}, this.ThrowInternetEmailOperationCompleted, userState);
        }
        
        private void OnThrowInternetEmailOperationCompleted(object arg) {
            if ((this.ThrowInternetEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ThrowInternetEmailCompleted(this, new ThrowInternetEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("FHWSoapValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ThrowPickList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceOut ThrowPickList(ServiceIn si) {
            object[] results = this.Invoke("ThrowPickList", new object[] {
                        si});
            return ((ServiceOut)(results[0]));
        }
        
        /// <remarks/>
        public void ThrowPickListAsync(ServiceIn si) {
            this.ThrowPickListAsync(si, null);
        }
        
        /// <remarks/>
        public void ThrowPickListAsync(ServiceIn si, object userState) {
            if ((this.ThrowPickListOperationCompleted == null)) {
                this.ThrowPickListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnThrowPickListOperationCompleted);
            }
            this.InvokeAsync("ThrowPickList", new object[] {
                        si}, this.ThrowPickListOperationCompleted, userState);
        }
        
        private void OnThrowPickListOperationCompleted(object arg) {
            if ((this.ThrowPickListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ThrowPickListCompleted(this, new ThrowPickListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("FHWSoapValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ThrowVoip", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceOut ThrowVoip(ServiceIn si) {
            object[] results = this.Invoke("ThrowVoip", new object[] {
                        si});
            return ((ServiceOut)(results[0]));
        }
        
        /// <remarks/>
        public void ThrowVoipAsync(ServiceIn si) {
            this.ThrowVoipAsync(si, null);
        }
        
        /// <remarks/>
        public void ThrowVoipAsync(ServiceIn si, object userState) {
            if ((this.ThrowVoipOperationCompleted == null)) {
                this.ThrowVoipOperationCompleted = new System.Threading.SendOrPostCallback(this.OnThrowVoipOperationCompleted);
            }
            this.InvokeAsync("ThrowVoip", new object[] {
                        si}, this.ThrowVoipOperationCompleted, userState);
        }
        
        private void OnThrowVoipOperationCompleted(object arg) {
            if ((this.ThrowVoipCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ThrowVoipCompleted(this, new ThrowVoipCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("FHWSoapValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ThrowWareless", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceOut ThrowWareless(ServiceIn si) {
            object[] results = this.Invoke("ThrowWareless", new object[] {
                        si});
            return ((ServiceOut)(results[0]));
        }
        
        /// <remarks/>
        public void ThrowWarelessAsync(ServiceIn si) {
            this.ThrowWarelessAsync(si, null);
        }
        
        /// <remarks/>
        public void ThrowWarelessAsync(ServiceIn si, object userState) {
            if ((this.ThrowWarelessOperationCompleted == null)) {
                this.ThrowWarelessOperationCompleted = new System.Threading.SendOrPostCallback(this.OnThrowWarelessOperationCompleted);
            }
            this.InvokeAsync("ThrowWareless", new object[] {
                        si}, this.ThrowWarelessOperationCompleted, userState);
        }
        
        private void OnThrowWarelessOperationCompleted(object arg) {
            if ((this.ThrowWarelessCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ThrowWarelessCompleted(this, new ThrowWarelessCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("FHWSoapValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ThrowUc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceOut ThrowUc(ServiceIn si) {
            object[] results = this.Invoke("ThrowUc", new object[] {
                        si});
            return ((ServiceOut)(results[0]));
        }
        
        /// <remarks/>
        public void ThrowUcAsync(ServiceIn si) {
            this.ThrowUcAsync(si, null);
        }
        
        /// <remarks/>
        public void ThrowUcAsync(ServiceIn si, object userState) {
            if ((this.ThrowUcOperationCompleted == null)) {
                this.ThrowUcOperationCompleted = new System.Threading.SendOrPostCallback(this.OnThrowUcOperationCompleted);
            }
            this.InvokeAsync("ThrowUc", new object[] {
                        si}, this.ThrowUcOperationCompleted, userState);
        }
        
        private void OnThrowUcOperationCompleted(object arg) {
            if ((this.ThrowUcCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ThrowUcCompleted(this, new ThrowUcCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("FHWSoapValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ThrowWWW", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceOut ThrowWWW(ServiceIn si) {
            object[] results = this.Invoke("ThrowWWW", new object[] {
                        si});
            return ((ServiceOut)(results[0]));
        }
        
        /// <remarks/>
        public void ThrowWWWAsync(ServiceIn si) {
            this.ThrowWWWAsync(si, null);
        }
        
        /// <remarks/>
        public void ThrowWWWAsync(ServiceIn si, object userState) {
            if ((this.ThrowWWWOperationCompleted == null)) {
                this.ThrowWWWOperationCompleted = new System.Threading.SendOrPostCallback(this.OnThrowWWWOperationCompleted);
            }
            this.InvokeAsync("ThrowWWW", new object[] {
                        si}, this.ThrowWWWOperationCompleted, userState);
        }
        
        private void OnThrowWWWOperationCompleted(object arg) {
            if ((this.ThrowWWWCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ThrowWWWCompleted(this, new ThrowWWWCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("FHWSoapValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ThrowVPN", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceOut ThrowVPN(ServiceIn si) {
            object[] results = this.Invoke("ThrowVPN", new object[] {
                        si});
            return ((ServiceOut)(results[0]));
        }
        
        /// <remarks/>
        public void ThrowVPNAsync(ServiceIn si) {
            this.ThrowVPNAsync(si, null);
        }
        
        /// <remarks/>
        public void ThrowVPNAsync(ServiceIn si, object userState) {
            if ((this.ThrowVPNOperationCompleted == null)) {
                this.ThrowVPNOperationCompleted = new System.Threading.SendOrPostCallback(this.OnThrowVPNOperationCompleted);
            }
            this.InvokeAsync("ThrowVPN", new object[] {
                        si}, this.ThrowVPNOperationCompleted, userState);
        }
        
        private void OnThrowVPNOperationCompleted(object arg) {
            if ((this.ThrowVPNCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ThrowVPNCompleted(this, new ThrowVPNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("FHWSoapValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ThrowTelPassword", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceOut ThrowTelPassword(ServiceIn si) {
            object[] results = this.Invoke("ThrowTelPassword", new object[] {
                        si});
            return ((ServiceOut)(results[0]));
        }
        
        /// <remarks/>
        public void ThrowTelPasswordAsync(ServiceIn si) {
            this.ThrowTelPasswordAsync(si, null);
        }
        
        /// <remarks/>
        public void ThrowTelPasswordAsync(ServiceIn si, object userState) {
            if ((this.ThrowTelPasswordOperationCompleted == null)) {
                this.ThrowTelPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnThrowTelPasswordOperationCompleted);
            }
            this.InvokeAsync("ThrowTelPassword", new object[] {
                        si}, this.ThrowTelPasswordOperationCompleted, userState);
        }
        
        private void OnThrowTelPasswordOperationCompleted(object arg) {
            if ((this.ThrowTelPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ThrowTelPasswordCompleted(this, new ThrowTelPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("FHWSoapValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ThrowNewTelPassword", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceOut ThrowNewTelPassword(ServiceIn si) {
            object[] results = this.Invoke("ThrowNewTelPassword", new object[] {
                        si});
            return ((ServiceOut)(results[0]));
        }
        
        /// <remarks/>
        public void ThrowNewTelPasswordAsync(ServiceIn si) {
            this.ThrowNewTelPasswordAsync(si, null);
        }
        
        /// <remarks/>
        public void ThrowNewTelPasswordAsync(ServiceIn si, object userState) {
            if ((this.ThrowNewTelPasswordOperationCompleted == null)) {
                this.ThrowNewTelPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnThrowNewTelPasswordOperationCompleted);
            }
            this.InvokeAsync("ThrowNewTelPassword", new object[] {
                        si}, this.ThrowNewTelPasswordOperationCompleted, userState);
        }
        
        private void OnThrowNewTelPasswordOperationCompleted(object arg) {
            if ((this.ThrowNewTelPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ThrowNewTelPasswordCompleted(this, new ThrowNewTelPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("FHWSoapValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ThrowSpecialNet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceOut ThrowSpecialNet(ServiceIn si) {
            object[] results = this.Invoke("ThrowSpecialNet", new object[] {
                        si});
            return ((ServiceOut)(results[0]));
        }
        
        /// <remarks/>
        public void ThrowSpecialNetAsync(ServiceIn si) {
            this.ThrowSpecialNetAsync(si, null);
        }
        
        /// <remarks/>
        public void ThrowSpecialNetAsync(ServiceIn si, object userState) {
            if ((this.ThrowSpecialNetOperationCompleted == null)) {
                this.ThrowSpecialNetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnThrowSpecialNetOperationCompleted);
            }
            this.InvokeAsync("ThrowSpecialNet", new object[] {
                        si}, this.ThrowSpecialNetOperationCompleted, userState);
        }
        
        private void OnThrowSpecialNetOperationCompleted(object arg) {
            if ((this.ThrowSpecialNetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ThrowSpecialNetCompleted(this, new ThrowSpecialNetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("FHWSoapValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ThrowNetwork", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceOut ThrowNetwork(ServiceIn si) {
            object[] results = this.Invoke("ThrowNetwork", new object[] {
                        si});
            return ((ServiceOut)(results[0]));
        }
        
        /// <remarks/>
        public void ThrowNetworkAsync(ServiceIn si) {
            this.ThrowNetworkAsync(si, null);
        }
        
        /// <remarks/>
        public void ThrowNetworkAsync(ServiceIn si, object userState) {
            if ((this.ThrowNetworkOperationCompleted == null)) {
                this.ThrowNetworkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnThrowNetworkOperationCompleted);
            }
            this.InvokeAsync("ThrowNetwork", new object[] {
                        si}, this.ThrowNetworkOperationCompleted, userState);
        }
        
        private void OnThrowNetworkOperationCompleted(object arg) {
            if ((this.ThrowNetworkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ThrowNetworkCompleted(this, new ThrowNetworkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("FHWSoapValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ThrowNetletter", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceOut ThrowNetletter(ServiceIn si) {
            object[] results = this.Invoke("ThrowNetletter", new object[] {
                        si});
            return ((ServiceOut)(results[0]));
        }
        
        /// <remarks/>
        public void ThrowNetletterAsync(ServiceIn si) {
            this.ThrowNetletterAsync(si, null);
        }
        
        /// <remarks/>
        public void ThrowNetletterAsync(ServiceIn si, object userState) {
            if ((this.ThrowNetletterOperationCompleted == null)) {
                this.ThrowNetletterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnThrowNetletterOperationCompleted);
            }
            this.InvokeAsync("ThrowNetletter", new object[] {
                        si}, this.ThrowNetletterOperationCompleted, userState);
        }
        
        private void OnThrowNetletterOperationCompleted(object arg) {
            if ((this.ThrowNetletterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ThrowNetletterCompleted(this, new ThrowNetletterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("FHWSoapValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidCostNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceOut ValidCostNo(ServiceIn si) {
            object[] results = this.Invoke("ValidCostNo", new object[] {
                        si});
            return ((ServiceOut)(results[0]));
        }
        
        /// <remarks/>
        public void ValidCostNoAsync(ServiceIn si) {
            this.ValidCostNoAsync(si, null);
        }
        
        /// <remarks/>
        public void ValidCostNoAsync(ServiceIn si, object userState) {
            if ((this.ValidCostNoOperationCompleted == null)) {
                this.ValidCostNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidCostNoOperationCompleted);
            }
            this.InvokeAsync("ValidCostNo", new object[] {
                        si}, this.ValidCostNoOperationCompleted, userState);
        }
        
        private void OnValidCostNoOperationCompleted(object arg) {
            if ((this.ValidCostNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidCostNoCompleted(this, new ValidCostNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("FHWSoapValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NewValidCostNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceOut NewValidCostNo(ServiceIn si) {
            object[] results = this.Invoke("NewValidCostNo", new object[] {
                        si});
            return ((ServiceOut)(results[0]));
        }
        
        /// <remarks/>
        public void NewValidCostNoAsync(ServiceIn si) {
            this.NewValidCostNoAsync(si, null);
        }
        
        /// <remarks/>
        public void NewValidCostNoAsync(ServiceIn si, object userState) {
            if ((this.NewValidCostNoOperationCompleted == null)) {
                this.NewValidCostNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNewValidCostNoOperationCompleted);
            }
            this.InvokeAsync("NewValidCostNo", new object[] {
                        si}, this.NewValidCostNoOperationCompleted, userState);
        }
        
        private void OnNewValidCostNoOperationCompleted(object arg) {
            if ((this.NewValidCostNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NewValidCostNoCompleted(this, new NewValidCostNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("FHWSoapValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidIEName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceOut ValidIEName(ServiceIn si) {
            object[] results = this.Invoke("ValidIEName", new object[] {
                        si});
            return ((ServiceOut)(results[0]));
        }
        
        /// <remarks/>
        public void ValidIENameAsync(ServiceIn si) {
            this.ValidIENameAsync(si, null);
        }
        
        /// <remarks/>
        public void ValidIENameAsync(ServiceIn si, object userState) {
            if ((this.ValidIENameOperationCompleted == null)) {
                this.ValidIENameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidIENameOperationCompleted);
            }
            this.InvokeAsync("ValidIEName", new object[] {
                        si}, this.ValidIENameOperationCompleted, userState);
        }
        
        private void OnValidIENameOperationCompleted(object arg) {
            if ((this.ValidIENameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidIENameCompleted(this, new ValidIENameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("FHWSoapValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFormStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceOut GetFormStatus(ServiceIn si) {
            object[] results = this.Invoke("GetFormStatus", new object[] {
                        si});
            return ((ServiceOut)(results[0]));
        }
        
        /// <remarks/>
        public void GetFormStatusAsync(ServiceIn si) {
            this.GetFormStatusAsync(si, null);
        }
        
        /// <remarks/>
        public void GetFormStatusAsync(ServiceIn si, object userState) {
            if ((this.GetFormStatusOperationCompleted == null)) {
                this.GetFormStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFormStatusOperationCompleted);
            }
            this.InvokeAsync("GetFormStatus", new object[] {
                        si}, this.GetFormStatusOperationCompleted, userState);
        }
        
        private void OnGetFormStatusOperationCompleted(object arg) {
            if ((this.GetFormStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFormStatusCompleted(this, new GetFormStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("FHWSoapValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryAccoutByGroup", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceOut QueryAccoutByGroup(ServiceIn si) {
            object[] results = this.Invoke("QueryAccoutByGroup", new object[] {
                        si});
            return ((ServiceOut)(results[0]));
        }
        
        /// <remarks/>
        public void QueryAccoutByGroupAsync(ServiceIn si) {
            this.QueryAccoutByGroupAsync(si, null);
        }
        
        /// <remarks/>
        public void QueryAccoutByGroupAsync(ServiceIn si, object userState) {
            if ((this.QueryAccoutByGroupOperationCompleted == null)) {
                this.QueryAccoutByGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryAccoutByGroupOperationCompleted);
            }
            this.InvokeAsync("QueryAccoutByGroup", new object[] {
                        si}, this.QueryAccoutByGroupOperationCompleted, userState);
        }
        
        private void OnQueryAccoutByGroupOperationCompleted(object arg) {
            if ((this.QueryAccoutByGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryAccoutByGroupCompleted(this, new QueryAccoutByGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class FHWSoap : System.Web.Services.Protocols.SoapHeader {
        
        private string userIDField;
        
        private string userPWDField;
        
        private string ipAddressField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public string UserPWD {
            get {
                return this.userPWDField;
            }
            set {
                this.userPWDField = value;
            }
        }
        
        /// <remarks/>
        public string IpAddress {
            get {
                return this.ipAddressField;
            }
            set {
                this.ipAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ServiceOut {
        
        private string infocodeField;
        
        private string messageField;
        
        private string statusField;
        
        /// <remarks/>
        public string Infocode {
            get {
                return this.infocodeField;
            }
            set {
                this.infocodeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ServiceIn {
        
        private string contentField;
        
        /// <remarks/>
        public string Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ThrowInternetEmailCompletedEventHandler(object sender, ThrowInternetEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ThrowInternetEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ThrowInternetEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ThrowPickListCompletedEventHandler(object sender, ThrowPickListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ThrowPickListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ThrowPickListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ThrowVoipCompletedEventHandler(object sender, ThrowVoipCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ThrowVoipCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ThrowVoipCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ThrowWarelessCompletedEventHandler(object sender, ThrowWarelessCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ThrowWarelessCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ThrowWarelessCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ThrowUcCompletedEventHandler(object sender, ThrowUcCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ThrowUcCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ThrowUcCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ThrowWWWCompletedEventHandler(object sender, ThrowWWWCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ThrowWWWCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ThrowWWWCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ThrowVPNCompletedEventHandler(object sender, ThrowVPNCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ThrowVPNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ThrowVPNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ThrowTelPasswordCompletedEventHandler(object sender, ThrowTelPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ThrowTelPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ThrowTelPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ThrowNewTelPasswordCompletedEventHandler(object sender, ThrowNewTelPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ThrowNewTelPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ThrowNewTelPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ThrowSpecialNetCompletedEventHandler(object sender, ThrowSpecialNetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ThrowSpecialNetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ThrowSpecialNetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ThrowNetworkCompletedEventHandler(object sender, ThrowNetworkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ThrowNetworkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ThrowNetworkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ThrowNetletterCompletedEventHandler(object sender, ThrowNetletterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ThrowNetletterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ThrowNetletterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ValidCostNoCompletedEventHandler(object sender, ValidCostNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidCostNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidCostNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void NewValidCostNoCompletedEventHandler(object sender, NewValidCostNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NewValidCostNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NewValidCostNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ValidIENameCompletedEventHandler(object sender, ValidIENameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidIENameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidIENameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetFormStatusCompletedEventHandler(object sender, GetFormStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFormStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFormStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void QueryAccoutByGroupCompletedEventHandler(object sender, QueryAccoutByGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryAccoutByGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryAccoutByGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceOut)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591